# 应用服务 WEB 访问端口
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

# 应用名称
spring:
  aop:
    auto: true
  application:
    name: shopping-kill
  # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/ftl/,classpath:/html/
  #环境修改
  profiles:
    active: dev,all

  devtools:
    restart:
      enabled: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    view:
      prefix: classpath:/html/

mybatis-plus:
  type-aliases-package: com.wsl.shoppingkill.constant
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

